#!/bin/bash
# This script will combine my VIMRC files into one, allowing for
# more portability of my configuration. The file generated here
# is not meant to be human readable, and will not include
# comments or whitespace from the original config files

set -e

filename="combined.vim"
files_dir="config"
init_file="init.vim"

function usage {
  cat >&2 <<EOF
Usage: $0 [-m]

Options
  -m            | Minimal configuration, excludes plugins
  -o [filename] | Outputs the combined file to filename (default 'combined.vim')
EOF
}

minimal=false

while getopts ":hmo:" opt; do
  case $opt in
    h) 
      usage
      exit 0
      ;;
    m)
      minimal=true
      ;;
    o)
      filename=$OPTARG
      ;;
    \?)
      echo "Unknown option -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument"
      usage
      exit 1
      ;;
  esac
done

if [[ -e $filename && -s $filename ]]; then
  while true; do
    read -p "File $filename exists, would you like to overwrite? [y/n] " yn
    case $yn in
      [yY])
        echo "Overwriting $filename and proceeding"
        break
        ;;
      [nN])
        echo "Will not overwrite $filename exiting"
        exit 0
        ;;
      *)
        echo "Please enter y or n"
        ;;
    esac
  done

fi

# Truncate the file to 0 length to start
: > $filename

if $minimal; then
  file_list=$(ls $files_dir | grep -v plugin)
  echo "Combining files without plugins into $filename..."
else
  file_list=$(ls $files_dir)
  echo "Combining files into $filename..."
fi


# First add the intro line to the combined file
cat >> $filename <<-EOF
" This is a combined vim configuration, generated by the combine script
" by Aaron Williamson. All unecessary whitespace and all comments other
" than this one have been removed.

EOF

# Then the init file, up until the exclude
LC_ALL=C sed -n -E 's/^[[:space:]]+(.*)/\1/g;s/([^[:space:]]+)[[:space:]]+([^[:space:]])/\1 \2/g;s/(^[^"]+) "[^"]+$/\1/;/$[[:space:]]*^|^"/!p;/--- EXCLUDE FROM COMBINED ---/q' $init_file >> $filename

for file in $file_list; do
  LC_ALL=C sed -n -E 's/^[[:space:]]+(.*)/\1/g;s/([^[:space:]]+)[[:space:]]+([^[:space:]])/\1 \2/g;s/(^[^"]+) "[^"]+$/\1/;/$[[:space:]]*^|^"/!p;/--- EXCLUDE FROM COMBINED ---/q' $files_dir/$file >> $filename
done

echo "Combination complete. Outputted to $filename"
